package cli

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"
)

// cmdComment implements `promptlock comment --github` (and a stdout-only mode
// for any other CI). Reads structured eval output from stdin or a file, renders
// a Markdown PR comment, and either prints it or upserts it onto a PR via the
// GitHub API.
func cmdComment(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("comment", flag.ContinueOnError)
	fs.SetOutput(stderr)
	useGitHub := fs.Bool("github", false, "POST/PATCH the comment to the GitHub PR identified by env vars")
	useMarkdown := fs.Bool("markdown", false, "print the rendered Markdown to stdout (default if --github not set)")
	fromFile := fs.String("from", "", "read eval JSON from this file instead of stdin")
	pr := fs.Int("pr", 0, "PR number (default: parse from $GITHUB_REF)")
	repo := fs.String("repo", "", "owner/repo (default: $GITHUB_REPOSITORY)")
	if err := parseFlexible(fs, args); err != nil {
		return ExitUsage
	}
	if !*useGitHub {
		*useMarkdown = true
	}

	var input []byte
	if *fromFile != "" {
		var err error
		input, err = os.ReadFile(*fromFile)
		if err != nil {
			fmt.Fprintln(stderr, "promptlock:", err)
			return ExitConfig
		}
	} else {
		var err error
		input, err = io.ReadAll(os.Stdin)
		if err != nil {
			fmt.Fprintln(stderr, "promptlock:", err)
			return ExitConfig
		}
	}

	// Strip UTF-8 BOM if present (PowerShell pipes inject one).
	if bytes.HasPrefix(input, []byte{0xEF, 0xBB, 0xBF}) {
		input = input[3:]
	}
	var payload map[string]any
	if err := json.Unmarshal(input, &payload); err != nil {
		fmt.Fprintln(stderr, "promptlock: comment input is not valid JSON:", err)
		return ExitConfig
	}
	md := renderMarkdown(payload)

	if *useMarkdown {
		fmt.Fprint(stdout, md)
		if !strings.HasSuffix(md, "\n") {
			fmt.Fprintln(stdout)
		}
	}
	if !*useGitHub {
		return ExitOK
	}

	repoStr := *repo
	if repoStr == "" {
		repoStr = os.Getenv("GITHUB_REPOSITORY")
	}
	if repoStr == "" {
		fmt.Fprintln(stderr, "promptlock: --repo not set and $GITHUB_REPOSITORY is empty")
		return ExitConfig
	}
	prNum := *pr
	if prNum == 0 {
		prNum = parsePRFromRef(os.Getenv("GITHUB_REF"))
	}
	if prNum == 0 {
		fmt.Fprintln(stderr, "promptlock: --pr not set and $GITHUB_REF doesn't look like refs/pull/<n>/...")
		return ExitConfig
	}
	token := os.Getenv("GITHUB_TOKEN")
	if token == "" {
		fmt.Fprintln(stderr, "promptlock: $GITHUB_TOKEN is not set (need contents:read + pull-requests:write)")
		return ExitConfig
	}

	if err := upsertGitHubComment(repoStr, prNum, token, md); err != nil {
		fmt.Fprintln(stderr, "promptlock:", err)
		return ExitConfig
	}
	fmt.Fprintln(stdout, "comment upserted on PR", prNum)
	return ExitOK
}

const commentMarker = "<!-- promptlock-comment v1 -->"

// renderMarkdown turns the eval JSON shape into a PR comment body.
func renderMarkdown(payload map[string]any) string {
	var b strings.Builder
	b.WriteString(commentMarker)
	b.WriteString("\n## promptlock eval results\n\n")
	results, _ := payload["results"].([]any)
	if len(results) == 0 {
		b.WriteString("_No prompts were evaluated for this PR._\n")
		return b.String()
	}

	anyFail := false
	b.WriteString("| Prompt | Metric | Score | Threshold | Provider | Result |\n")
	b.WriteString("|--------|--------|-------|-----------|----------|--------|\n")
	for _, ri := range results {
		r, _ := ri.(map[string]any)
		if r == nil {
			continue
		}
		promptID, _ := r["prompt_id"].(string)
		errMsg, _ := r["error"].(string)
		runs, _ := r["runs"].([]any)
		if errMsg != "" {
			anyFail = true
			fmt.Fprintf(&b, "| `%s` | — | — | — | — | ❌ %s |\n", promptID, errMsg)
			continue
		}
		for _, run := range runs {
			rm, _ := run.(map[string]any)
			if rm == nil {
				continue
			}
			passed, _ := rm["passed"].(bool)
			if !passed {
				anyFail = true
			}
			marker := "✅"
			if !passed {
				marker = "❌"
			}
			score, _ := rm["score"].(float64)
			thr, _ := rm["threshold"].(float64)
			metric, _ := rm["metric"].(string)
			provider, _ := rm["provider"].(string)
			fmt.Fprintf(&b, "| `%s` | `%s` | %.3f | %.2f | %s | %s |\n",
				promptID, metric, score, thr, provider, marker)
		}
	}
	if anyFail {
		b.WriteString("\n> One or more evals are below threshold. Update the prompt or run `promptlock lock` to accept the new baseline.\n")
	} else {
		b.WriteString("\n> All evals passed.\n")
	}
	b.WriteString("\n<sub>Generated by [promptlock](https://github.com/promptlock/promptlock).</sub>\n")
	return b.String()
}

func parsePRFromRef(ref string) int {
	// refs/pull/123/merge or refs/pull/123/head
	if !strings.HasPrefix(ref, "refs/pull/") {
		return 0
	}
	rest := strings.TrimPrefix(ref, "refs/pull/")
	slash := strings.IndexByte(rest, '/')
	if slash <= 0 {
		return 0
	}
	var n int
	if _, err := fmt.Sscanf(rest[:slash], "%d", &n); err != nil {
		return 0
	}
	return n
}

func upsertGitHubComment(repo string, pr int, token, body string) error {
	api := "https://api.github.com"
	client := &http.Client{Timeout: 30 * time.Second}

	// 1. List existing comments on the PR; find ours by marker.
	listURL := fmt.Sprintf("%s/repos/%s/issues/%d/comments?per_page=100", api, repo, pr)
	req, _ := http.NewRequest("GET", listURL, nil)
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("X-GitHub-Api-Version", "2022-11-28")
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("github list comments: %w", err)
	}
	respBody, _ := io.ReadAll(resp.Body)
	resp.Body.Close()
	if resp.StatusCode >= 400 {
		return fmt.Errorf("github list comments: %d: %s", resp.StatusCode, snippet(respBody))
	}
	var existing []struct {
		ID   int64  `json:"id"`
		Body string `json:"body"`
	}
	if err := json.Unmarshal(respBody, &existing); err != nil {
		return fmt.Errorf("github list decode: %w", err)
	}

	payload, _ := json.Marshal(map[string]string{"body": body})

	for _, c := range existing {
		if strings.Contains(c.Body, commentMarker) {
			patchURL := fmt.Sprintf("%s/repos/%s/issues/comments/%d", api, repo, c.ID)
			r, _ := http.NewRequest("PATCH", patchURL, bytes.NewReader(payload))
			r.Header.Set("Authorization", "Bearer "+token)
			r.Header.Set("Content-Type", "application/json")
			r.Header.Set("Accept", "application/vnd.github+json")
			r.Header.Set("X-GitHub-Api-Version", "2022-11-28")
			pr, err := client.Do(r)
			if err != nil {
				return fmt.Errorf("github patch: %w", err)
			}
			pb, _ := io.ReadAll(pr.Body)
			pr.Body.Close()
			if pr.StatusCode >= 400 {
				return fmt.Errorf("github patch: %d: %s", pr.StatusCode, snippet(pb))
			}
			return nil
		}
	}

	// 2. No existing — POST a new one.
	postURL := fmt.Sprintf("%s/repos/%s/issues/%d/comments", api, repo, pr)
	r, _ := http.NewRequest("POST", postURL, bytes.NewReader(payload))
	r.Header.Set("Authorization", "Bearer "+token)
	r.Header.Set("Content-Type", "application/json")
	r.Header.Set("Accept", "application/vnd.github+json")
	r.Header.Set("X-GitHub-Api-Version", "2022-11-28")
	pr2, err := client.Do(r)
	if err != nil {
		return fmt.Errorf("github post: %w", err)
	}
	pb, _ := io.ReadAll(pr2.Body)
	pr2.Body.Close()
	if pr2.StatusCode >= 400 {
		return fmt.Errorf("github post: %d: %s", pr2.StatusCode, snippet(pb))
	}
	return nil
}

func snippet(b []byte) string {
	const max = 200
	s := strings.TrimSpace(string(b))
	if len(s) > max {
		return s[:max] + "…"
	}
	return s
}
